### ISSUE TITLE
Diagnostic Line Numbers are offset by one in certain situations

### ISSUE THREAD

**Issue by hahuang65** [jmbuhr/otter.nvim#115]
With file `after/ftplugin/markdown.lua` having the contents of

```
require("otter").activate({ "python" }, true, true, nil)
```

If I open `nvim .` and navigate to `notebooks/notebook.ipynb` to open it, `otter` will activate, and have the diagnostics offset by 1 line.

If I directly open `nvim notebooks/notebook.ipynb`, the code in `after/ftplugin/markdown.lua` will not trigger (not sure why), but calling `require("otter").activate({ "python" }, true, true, nil)` manually will cause diagnostics to appear on the correct line.

Similarly, if I don't have the `after/ftplugin/markdown.lua`, and manually activate otter, no matter how I open it, the offset issue does not exist.

Originally thought this was a molten issue, but after discussing in https://github.com/benlubas/molten-nvim/issues/178 I've discovered it's more likely something in `otter.nvim`

**Comment by benlubas** [comment]
I looks like we write the otter buffer with line numbers off by one, and the original time that we grab diagnostics this isn't accounted for. I'm slightly confused on why it's only in this one situation though. 

I'll note that the diagnostics do update correctly after writing the file or changing it to cause a diagnostic update in the otter buffer.

**Comment by hahuang65** [comment]
What's strange to me is... why does it happen when it's done quickly (via `ftplugin/markdown.lua`), but not when run manually after the file is opened. 

I assume the operations are the same. Would it have something to do with the timing of Jupytext.nvim completing?

**Comment by jmbuhr** [comment]
Interesting. This is where jupytext sets the filetype, so it is when otter would kick in: https://github.com/GCBallesteros/jupytext.nvim/blob/6e439dc048986bcc00f8ba8695cb452de932127b/lua/jupytext/init.lua#L139

**Comment by benlubas** [comment]
https://github.com/GCBallesteros/jupytext.nvim/blob/6e439dc048986bcc00f8ba8695cb452de932127b/lua%2Fjupytext%2Finit.lua#L149

Lmao. This bug is as dumb as I thought it might be. Otter is doing nothing wrong here. I think they're deleting and not writing afterward so otter doesn't pick up the change (bc sync raft isn't called after this delete).

**Comment by benlubas** [comment]
Easy fix is rearranging the code in there so filetype is set after. I can open a PR in a little bit when I'm more awake.

**Comment by jmbuhr** [comment]
hm, technically this isn't even a bug then. Otter diagnostics get updated on write and it's up to the user do the writing or choose additional auto command events on which to do the updates (see otter config). Nonetheless it would of course be great if they changed it in the way proposed by Ben, but I would frame it as doing us a favor instead of fixing a bug or hack.

**Comment by benlubas** [comment]
Yup, definitely not a 'bug' more of an unfortunate side effect.

**Comment by benlubas** [comment]
@hahuang65 this should be resolved now if you update jupytext.nvim

**Comment by hahuang65** [comment]
@benlubas thanks so much. Verified that it's fixed.
Thanks for your help and patience thru this "bug" journey.
