### ISSUE TITLE
bug: handle_leading_whitespace seems to delete all whitespace (?)

### ISSUE THREAD

**Issue by benlubas** [jmbuhr/otter.nvim#159]
with 0 indent at all, it's fine:
![image](https://github.com/jmbuhr/otter.nvim/assets/56943754/87e9d491-6aa1-47e4-834b-75b445cb195d)

With 2 space indent on both lines it's fine: 
![image](https://github.com/jmbuhr/otter.nvim/assets/56943754/175631d2-d83c-4680-bce6-ee0857eff6bd)

But with 0 leading indent on the code block itself, I do not get correct completions when I'm in an if block.
![image](https://github.com/jmbuhr/otter.nvim/assets/56943754/f428efd5-8332-494d-bb04-c08a7a2389d4)

**Comment by benlubas** [comment]
Hmmm. It seems like it works if there aren't any 0-indent blocks, and only fails when there are a mix of 0-indent and n-indent code blocks in the document

**Comment by jmbuhr** [comment]
I assume the code is all there in the otter buffer, so our `keeper.sync_raft` code works?

Can you `vim.print` the `params` of the completion requests before and after we modify the positions here:
https://github.com/jmbuhr/otter.nvim/blob/5f03444012b44f3715413f51b47ba2b3607cd1be/lua/otter/lsp/init.lua#L142-L144
Maybe we are missing something. If this is not the case it is something harder to spot.

I previously had issues with the other lsp servers like pyright being out of sync, see
https://github.com/jmbuhr/otter.nvim/blob/5f03444012b44f3715413f51b47ba2b3607cd1be/lua/otter/init.lua#L125-L129
What was happening there is as follows. Lsp servers don't actually look at the buffer (most of the time, for pyright we even disable it explicitly due to a bug https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/6455ad9123041f11e3294508db8f216223e2ca8a/lua/plugins/lsp.lua#L288-L296) content. The client (neovim) sends a `didOpen` notification with the content of the buffer to the server and every time the content is changed it sends the changes over. In our case, we don't need to send these notifications, they get sent automatically by nvim when we change the otter buffer because pyright is `attached` to that buffer (that's mostly what being attached entails). But if for some reason one of these notifications gets lost the server gets confused. Just something to keep in mind in case nothing else makes sense.

**Comment by jmbuhr** [comment]
Also, I can not reproduce this with `./tests/debug_example.sh 05.norg`
![image](https://github.com/jmbuhr/otter.nvim/assets/17450586/0a16f815-4fa2-450c-a159-f6696288209a)

**Comment by jmbuhr** [comment]
What file do you experience the issue with and how do you activate otter?

**Comment by benlubas** [comment]
Here's the file:

<details>
<summary> file </summary>

```norg
@code python
y = []
y.pop()
if True:
  y.append(1)
@end

* Heading
  @code python
  print("hi there")
  x = []
  y_2 = x.copy()

  y.pop()

  while True:
    x.clear()
    for i in range(10):
      x.append(i)
    break
  @end

```

</details>

I activate it with a dev version of the Neorg otter integration, which is [here](https://github.com/benlubas/neorg/tree/push-rmokpvyqqtmr). The relevant lines are:

```lua
otter.activate(
    module.config.public.languages, -- I have set to { "python", "lua" }
    module.config.public.completion.enabled, -- true
    module.config.public.diagnostics.enabled, -- true
    nil
)
```

The above integration is only providing user commands and making sure that `handle_leading_whitespace` is set to true.

**Comment by benlubas** [comment]
I can print and inspect in a little bit, I've got a bunch of random stuff to do today, you don't have to look into this for now, I'll try to get a consistent reproduction

**Comment by jmbuhr** [comment]
Ok. As another test, it is always interesting if activating otter manually after opening a file makes a difference compared to an autocommand or ftplugin, to rule out races with other plugins (like in this case: https://github.com/jmbuhr/otter.nvim/issues/154#issuecomment-2211434551 ).

**Comment by jmbuhr** [comment]
And while we are at it, I want to eventually take the `otter.keeper.modify_position` code and split it up explicitly for each request method, such that we don't unnecessarily check params for all sorts of positions for every request, so if destructuring this happens to become part of your debugging process I'd be happy about a PR :)

**Comment by jmbuhr** [comment]
Something else must be going on here. If I take your file and and just add an autocommand to activate otter for norg
```lua
vim.api.nvim_create_autocmd({ "BufReadPost" }, {
    desc = "Activate Otter on Buf Enter",
    pattern = "*.norg",
    group = vim.api.nvim_create_augroup("NorgOtter", {}),
    callback = function(_)
      require'otter'.activate()
    end,
})
```
it just works. Same as activating manually.
However, I don't have anything else configured for Norg. Does the Norg plugin modify the buffer in any way after opening?

**Comment by jmbuhr** [comment]
Btw. as you can see in the autocommand, you don't have to necessarily pass languages to otter.activate, it creates otters for all languages found (and for which it knows file extensions) by default.

**Comment by benlubas** [comment]
Neorg doesn't alter the buffer after opening.

**Comment by benlubas** [comment]
I'm unable to reproduce it in ~5 minutes of playing around with it. I'll reopen if I find a reproduction
