### ISSUE TITLE
popup/hover support. Activate otter for lsp hover popup scratch buffer crashes.

### ISSUE THREAD

**Issue by kaddkaka** [jmbuhr/otter.nvim#189]
I just got informed about this really cool lsp and thought I could use it for vim.lsp.buf.hover() but am experiencing some difficulties. Is this an intended usecase?

# Scenario 1
When pressing `K` to get lsp hover popup I can press it again to enter into the popup:

![image](https://github.com/user-attachments/assets/0d35f513-e626-45ef-b24c-eaeac6853dcc)

Once hear I can activate otter but the zig code in the markdown is not really formatted such that zls understands/accepts it. (The red box indicate a diagnostics error). I guess this would be something for the zig lsp to improve upon if they think it's an interesting usecase?

# Scenario 2 (crash)
When I try to activate otter for my second lsp hover popup using `:lua require'otter'.activate({'zig'})` I receive this error:

```
E5108: Error executing lua .../.local/share/nvim/plugged/otter.nvim/lua/otter/init.lua:95: Vim:E95: Buffer with this name already exists
stack traceback:
        [C]: in function 'nvim_buf_set_name'
        .../.local/share/nvim/plugged/otter.nvim/lua/otter/init.lua:95: in function 'activate'
        [string ":lua"]:1: in main chunk
```

Could it be that each popup I open has the same buffer name `[scratch]` and that causes a conflict in otter?

**Comment by jmbuhr** [comment]
It is an interesting idea and I thought about trying this myself, but decided in the end that doing this directly with hover windows is more of a chain of edgecases for very little benefit. Mostly because those scratch buffers are indeed meant to be ephemeral, messing with this is bound to break things. In many cases it can be achieve manually, but it is highly dependent on the language. For example, here is how you could do it manually for python hovers (some.. depends on how the docstrings are written):

https://github.com/user-attachments/assets/437c6209-626a-4a03-a0a4-36f38d3899f8

**Comment by jmbuhr** [comment]
writing the scratch buffer to a file and opening that could of course be automated with a keybinding, but that's something for a personal config, not otter.

**Comment by kaddkaka** [comment]
Yes, this makes a lot of sense. Thank you for the screencast explanation :+1: I didn't know about `<ctrl-w>T`. :)
