### ISSUE TITLE
Document the configuration process for something other than quarto

### ISSUE THREAD

**Issue by Antonio-Rocchia** [jmbuhr/otter.nvim#50]
The README page points to the quarto kickstart configuration but it does not show how to configure otter.nvim for other very useful use cases such as web development

**Comment by jmbuhr** [comment]
That sounds like an interesting usecase indeed, what is the context you are working on in which you have languages embedded within each other?

**Comment by jmbuhr** [comment]
I believe the reason that there wasn't that big of a need for extra completion of js inside of html is that they are so intertwined, they are better handled by a language server that understands the context of your whole project, which again is often framework-specific. Say for example you are using [svelt](https://svelte.dev/), you might have a `.svelte` file with html and js that looks like this:
```svelte
<script>
	let count = 0;

	function increment() {
		count += 1;
	}
</script>

<button on:click={increment}>
	Clicked {count}
	{count === 1 ? 'time' : 'times'}
</button>
```

Now, `count` is referenced both in the html and the js. The svelte langue server (which you can just use in Neovim) will know what to do with that, because it sees the whole file.

But otter.nvim can only look at the js code in isolation and attach a generic java script language server to that, which won't have as much information as a framework-specific one.

**Comment by jmbuhr** [comment]
I did make one change in the latest otter.nvim to properly detect script tags in html, so if you have a java script language server configured you can try it by calling `:lua require'otter'.activate({'javascript'}` in your html file. This only creates the otter buffer and activates completion + diagnostics, it does not set any keybindings.
