### ISSUE TITLE
otter buffers sometimes stick around as files

### ISSUE THREAD

**Issue by jmbuhr** [jmbuhr/otter.nvim#7]
by being accidentally saved.

**Comment by jmbuhr** [comment]
~swap files also sometimes stick around.

**Comment by jolars** [comment]
Maybe this is the problem that I'm facing. 

I am on I3 and have a problem where the swap files created from otter (or possibly quarto-nvim), e.g. `file-name.qmd-tmp.R.swp` stick around after quitting neovim using the usual close window command. If I quit the buffer using `:q` in neovim first, then close, then everything works fine. But if I just close neovim then the swap files remain and I get `Found a swap file by the name ...` and an error related to autocommands.

**Comment by FergusFettes** [comment]
Hey, absolutely love these repos, you guys are doing the lords work. I literally made a blog now I like using Quarto and Nvim so much. Thanks!

I'm seeing this issue-- on `:wq` cant close because `myfile.qmd-tmp.py` is open in another buffer.

(Simplest short term fix is `:wq!` or so obviously.)

I guess this is the same bug?

I wanted to find a simple way to reproduce it, but it just seems to happen after some time, can't tell exactly why.

**Comment by jmbuhr** [comment]
I also haven't found a consisten way of triggering it. I used to think it was because I have a habit of saving or quit+saving all with `:wa` or `:xa`, but I have also found it to happen when I have definitely not used those.

It might be that when the main buffer is edited and the otter buffer updated accordingly this counts as a change and so nvim won't close a changed buffer. There must be a way of telling nvim that the changes otter.nvim does are not changes it should worry about.
