### ISSUE TITLE
[Question] How to turn off diagnostic

### ISSUE THREAD

**Issue by Bekaboo** [jmbuhr/otter.nvim#75]
Sometimes the code snippets inside a code block do not necessarily have to use a complete and correct syntax, but I do not want to have diagnostic hints for these blocks. For example, the following error is pretty annoying:

![image](https://github.com/jmbuhr/otter.nvim/assets/76579810/10d5d82b-6bba-4be7-9a7f-ef728d2cdccb)

Thanks in advance!

**Comment by jmbuhr** [comment]
Depending on the markdown flavor you are using you can differentiate between code chunks that need to be syntactically correct (because they will be executed at render time) and those that only add syntax highlighting. e.g. for Quarto we activate `otter` like this:
https://github.com/quarto-dev/quarto-nvim/blob/0a35b3890e9d723b730506d7d8b3ba3d0d6aae2e/lua/quarto/init.lua#L93-L117

This will enable code features only for code code chunks of the form

````
```{python}
```
````

but not for

````
```python
```
````

**Comment by Bekaboo** [comment]
@jmbuhr Hi, thanks for reply. However I still don't understand how to disable it. I am using markdown not quarto, and it is not likely I will switch to quarto, could I still disable diagnostic in this case? Is there an option like `diagnostic = false` or `vim.g.otter_diagnostic = false` (so that I can disable it globally, which is fine for me)?

**Comment by jmbuhr** [comment]
Yes, you can just pass `false` to `diagnostics` when you `activate` otter:
https://github.com/jmbuhr/otter.nvim/blob/9a3db06bf3abadafb93279648317984ca789b888/lua/otter/init.lua#L44

**Comment by Bekaboo** [comment]
Thanks!
